# Generated by Django 3.0.7 on 2020-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=12)),
                ('description', models.CharField(max_length=25)),
                ('small_price', models.IntegerField()),
                ('large_price', models.IntegerField()),
            ],
        ),
    ]
