# Generated by Django 3.0.7 on 2020-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image_url',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
