# Generated by Django 3.0.7 on 2020-06-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pizza_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image_url',
            field=models.TextField(),
        ),
    ]
