# Generated by Django 3.0.7 on 2020-06-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200617_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
