# Generated by Django 3.0.7 on 2020-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200617_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='small_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
