# Generated by Django 3.0.7 on 2020-06-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200617_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraForSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lage_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('extras', models.ManyToManyField(blank=True, related_name='subs', to='orders.ExtraForSub')),
            ],
        ),
    ]
