# Generated by Django 3.0.7 on 2020-06-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200618_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='image_url',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
