# Generated by Django 3.0.7 on 2020-06-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_pasta_salad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='image_url',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salad',
            name='image_url',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
