# Generated by Django 3.0.7 on 2020-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_dinnerplatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_by', models.CharField(max_length=25)),
                ('confirmed_by_restaurant', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
