# Generated by Django 3.0.7 on 2020-06-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_checkoutorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorders',
            name='order_details',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
